before_install:
  - openssl aes-256-cbc -K $encrypted_e4f011a99370_key -iv $encrypted_e4f011a99370_iv -in ./lib/fit.jar.enc -out ./lib/fit.jar -d

language: scala

scala:
  - 2.12.8
  - 2.11.12

jdk:
  - oraclejdk8
